import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';
import solidPlugin from 'vite-plugin-solid';
import { semiSolidPlugin } from './packages/compiler/src/plugin';
import { createBrandResolver } from './packages/compiler/src/brand-resolve';

const brand = process.env.BRAND || 'brand-a';
const locale = process.env.LOCALE || 'en';
const outDir = `dist/${brand}/${locale}`;

// When emptyOutDir is false, Vite adds the outDir to its file watcher to
// detect external changes. Our plugin uses writeIfChanged() so it only touches
// files whose content actually changed, avoiding spurious mtime updates that
// would re-trigger the watcher. build.watch.exclude is a belt-and-suspenders
// guard, but must only be non-null during actual watch builds (a non-null
// value enables watch mode even without the --watch flag).
const isWatchMode = process.argv.some((a) => a === '--watch' || a === '-w');

export default defineConfig({
  plugins: [
    tailwindcss(),
    createBrandResolver(brand),
    // semiSolidPlugin MUST come before solidPlugin: both use enforce:'pre' and
    // Vite runs them in array order within the pre-phase. Our plugin needs to
    // see raw JSX source; solidPlugin transforms JSX away before we can parse it.
    semiSolidPlugin({ brand, locale, outDir }),
    solidPlugin(),
  ],
  resolve: {
    alias: {
      '$lib': '/packages/solid/src',
      // Category aliases mirror Shopify's output structure (snippets, sections, blocks).
      // Vite's alias plugin runs before all user plugins, so these aliases are the
      // effective resolver for base components. Brand overrides are handled by the
      // brand resolver plugin which intercepts $snippets/$sections/$blocks prefixes.
      '$snippets': '/src/snippets',
      '$sections': '/src/sections',
      '$blocks': '/src/blocks',
      '$brand': `/src/brands/${brand}`,
    },
  },
  build: {
    outDir,
    // Do not wipe dist/ before each build. Shopify CLI watches the dist
    // directory and will delete theme files it no longer sees locally.
    // In watch mode Vite only re-transforms changed modules, so previously
    // generated liquid files must persist on disk between incremental builds.
    emptyOutDir: false,
    // Exclude the output directory from the file watcher in watch mode.
    // Without this, closeBundle()'s writes to dist/ are picked up by Vite's
    // watcher (which it adds because emptyOutDir is false) and trigger an
    // immediate re-build → infinite loop. Note: a non-null build.watch value
    // would enable watch mode for regular builds too, so we only set it when
    // the --watch flag is actually present.
    watch: isWatchMode ? { exclude: `${outDir}/**` } : null,
    rollupOptions: {
      // Phase 3+: route files as entry points.
      // Each route compiles to a JS bundle + liquid template.
      // virtual:semi-solid/hydration-entry is generated by the plugin and
      // bundled by Vite so solid-js/web and $components/* are fully resolved —
      // no bare module specifiers reach the browser.
      input: {
        layout: 'src/routes/+layout.tsx',
        index: 'src/routes/index.tsx',
        product: 'src/routes/products/[handle].tsx',
        collection: 'src/routes/collections/[handle].tsx',
        'theme.entry': 'virtual:semi-solid/hydration-entry',
      },
      output: {
        // No content hashes in asset filenames. Shopify's CDN handles
        // cache-busting via its own versioning, and stable filenames mean
        // theme-assets.liquid never needs updating just because CSS changed.
        // They also prevent stale hashed files accumulating in dist/ when
        // emptyOutDir is false.
        entryFileNames: 'assets/[name].js',
        chunkFileNames: 'assets/[name].js',
        assetFileNames: 'assets/[name][extname]',
      },
    },
  },
});
