/**
 * +layout.tsx — Shopify theme layout
 *
 * Compiles to layout/theme.liquid. The {props.children} slot becomes
 * {{ content_for_layout }}, which Shopify uses to inject the active template.
 *
 * liquidRaw() is used for Liquid expressions that have no JSX equivalent.
 * At build time they pass through to .liquid unchanged; at runtime they
 * return '' so the component still works in tests and Storybook.
 */

import '$brand/theme.css';
import { tap, liquidRaw } from '$lib/runtime';
import HeaderMenu from '$snippets/HeaderMenu';
import PredictiveSearch from '$snippets/PredictiveSearch';
import MiniCart from '$snippets/MiniCart';

interface LayoutProps {
  children?: unknown;
}

export default function Layout(props: LayoutProps) {
  const shopName = tap('{{ shop.name }}', 'My Store');

  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{shopName}</title>
        {/* Shopify injects its own scripts and analytics here — required. */}
        {liquidRaw('{{ content_for_header }}')}
        {/* CSS + JS asset includes generated by the semi-solid compiler. */}
        {liquidRaw("{% render 'theme-assets' %}")}
      </head>
      <body class="bg-surface text-text font-body min-h-screen flex flex-col">
        <header class="border-b border-gray-200 sticky top-0 z-30 bg-white/95 backdrop-blur-sm">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 py-3 flex items-center gap-4">
            <a href="/" class="text-xl font-bold text-primary mr-6 shrink-0">{shopName}</a>
            <HeaderMenu />
            <div class="ml-auto flex items-center gap-2">
              <PredictiveSearch />
              <MiniCart />
            </div>
          </div>
        </header>
        <main class="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 py-8">
          {props.children}
        </main>
        <footer class="border-t border-gray-200 mt-auto">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 py-6">
            <p class="text-sm text-gray-500">&copy; {shopName}</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
